apiVersion: v1
kind: Service
metadata:
  name: todo-deployment-svc
spec:
  selector:
    app: todo
  ports:
    - name: http
      port: 8082
      protocol: TCP
      targetPort: 8082
  type: LoadBalancer